DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0044"] = [
	{ "s": "DE", "p": [3, 8, 12, 11, 9, 1, 7, 10, 6, 4, 5, 2] },
	{ "s": "DEBEN", "p": [11, 10, 9, 8, 7, 6, 5, 4, 3] },
	{ "s": "DEFECTO", "p": [12] },
	{ "s": "DEFINE", "p": [3] },
	{ "s": "DEJAR", "p": [6] },
	{ "s": "DEL", "p": [12, 3, 11, 1, 10, 9, 8, 6, 5, 4] },
	{ "s": "DEPENDA", "p": [6] },
	{ "s": "DEPENDENCIAS", "p": [12] },
	{ "s": "DERECHA", "p": [3] },
	{ "s": "DESARROLLO", "p": [12] },
	{ "s": "DESCRIPCIÓN", "p": [6, 3, 9, 8] },
	{ "s": "DESDE", "p": [12, 3] },
	{ "s": "DESEANDO", "p": [1] },
	{ "s": "DESTINADA", "p": [1] },
	{ "s": "DICHA", "p": [9] },
	{ "s": "DIRECCIÓN", "p": [11] },
	{ "s": "DIRECTORIO", "p": [12] },
	{ "s": "DISEÑADA", "p": [11, 10, 9, 8, 7, 6, 5, 4, 3] },
	{ "s": "DISPONIBLE", "p": [3] },
	{ "s": "DISPONIBLES", "p": [3] },
	{ "s": "DISPOSITIVO", "p": [3] },
	{ "s": "DIVERSIFICARLOS", "p": [1] },
	{ "s": "DNI", "p": [11] },
	{ "s": "DOCKER", "p": [12] },
	{ "s": "DOCKER-COMPOSE", "p": [12] },
	{ "s": "DOCUMENTACIÓN", "p": [1] },
	{ "s": "DOCUMENTO", "p": [11, 9] },
	{ "s": "DR", "p": [1] },
	{ "s": "DR.EXPLAIN", "p": [1] }
];