DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0043"] = [
	{ "s": "CAMISAS", "p": [6] },
	{ "s": "CAMPO", "p": [7, 10, 6, 5, 4, 3] },
	{ "s": "CAMPOS", "p": [3, 11, 10, 9, 8, 7, 6, 5, 4] },
	{ "s": "CANTIDAD", "p": [3] },
	{ "s": "CARACTERÍSTICAS", "p": [1] },
	{ "s": "CARGAR", "p": [3] },
	{ "s": "CASO", "p": [6] },
	{ "s": "CATALOGO", "p": [9, 8] },
	{ "s": "CATEGORÍA", "p": [6, 3] },
	{ "s": "CD", "p": [12] },
	{ "s": "CELULAR", "p": [10, 4, 11] },
	{ "s": "CLIC", "p": [3] },
	{ "s": "CLIENTE", "p": [11] },
	{ "s": "CLONA", "p": [12] },
	{ "s": "CLONAR", "p": [12] },
	{ "s": "CLONE", "p": [12] },
	{ "s": "CODE", "p": [12] },
	{ "s": "COLOCAR", "p": [9, 8] },
	{ "s": "COM", "p": [12] },
	{ "s": "COMO", "p": [9] },
	{ "s": "COMPLETADOS", "p": [11, 10, 9, 8, 7, 6, 5, 4, 3] },
	{ "s": "COMPLETAR", "p": [11, 10, 9, 8, 7, 6, 5, 4, 3] },
	{ "s": "COMPLETES", "p": [3, 11, 10, 9, 8, 7, 6, 5, 4] },
	{ "s": "COMPOSE", "p": [12] },
	{ "s": "COMPRA", "p": [8, 9] },
	{ "s": "COMPRARLO", "p": [3] },
	{ "s": "COMUNICARSE", "p": [12] },
	{ "s": "CON", "p": [12, 4, 3, 11, 10, 9, 8, 7, 6, 5] },
	{ "s": "CONEXIÓN", "p": [12] },
	{ "s": "CONFIGURACIÓN", "p": [12] },
	{ "s": "CONFIGURADO", "p": [12] },
	{ "s": "CONFIGURAR", "p": [12] },
	{ "s": "CONFIRMADO", "p": [9] },
	{ "s": "CONFIRMAR", "p": [12] },
	{ "s": "CONTACTARNOS", "p": [1] },
	{ "s": "CONTENEDORES", "p": [12] },
	{ "s": "CONTENIDO", "p": [1] },
	{ "s": "CONTINUACIÓN", "p": [11, 10, 9, 8, 7, 6, 5, 4, 3] },
	{ "s": "CONTRASEÑA", "p": [4] },
	{ "s": "CORRECTAMENTE", "p": [11, 10, 9, 8, 7, 6, 5, 4, 3] },
	{ "s": "CORRIENDO", "p": [12] },
	{ "s": "CP", "p": [12] },
	{ "s": "CREACIÓN", "p": [1] },
	{ "s": "CREAR", "p": [8, 6, 4, 11, 10, 7, 5, 3, 9] },
	{ "s": "CUAL", "p": [9, 8] },
	{ "s": "CUALQUIER", "p": [12] },
	{ "s": "CUESTA", "p": [3] },
	{ "s": "CÓDIGO", "p": [12] },
	{ "s": "CÓMODO", "p": [1] },
	{ "s": "CÓPIALO", "p": [12] }
];