DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0050"] = [
	{ "s": "PADRE", "p": [6] },
	{ "s": "PAGO", "p": [9] },
	{ "s": "PARA", "p": [3, 6, 4, 12, 11, 10, 9, 8, 7, 5, 1] },
	{ "s": "PARTE", "p": [11, 10, 9, 8, 7, 6, 5, 4] },
	{ "s": "PASO", "p": [12] },
	{ "s": "PASOS", "p": [11, 10, 9, 8, 7, 6, 5, 4, 3] },
	{ "s": "PERMISOS", "p": [9] },
	{ "s": "PERSONALÍZALO", "p": [12] },
	{ "s": "PERTENECE", "p": [3] },
	{ "s": "PLANTILLA", "p": [1] },
	{ "s": "POLOS", "p": [6] },
	{ "s": "POR", "p": [1, 12, 4] },
	{ "s": "PRECIO", "p": [3] },
	{ "s": "PREGUNTAS", "p": [1] },
	{ "s": "PRESIONA", "p": [3, 11, 10, 9, 8, 7, 6, 5, 4] },
	{ "s": "PRESIONE", "p": [9, 8] },
	{ "s": "PREVIOS", "p": [12] },
	{ "s": "PRINCIPAL", "p": [6, 1] },
	{ "s": "PROBLEMA", "p": [11, 10, 9, 8, 7, 6, 5, 4, 3] },
	{ "s": "PRODUCTO", "p": [3, 9, 8, 1] },
	{ "s": "PRODUCTOS", "p": [3, 9, 8] },
	{ "s": "PROPORCIONADO", "p": [7, 10, 6, 5, 4, 3] },
	{ "s": "PROVEEDOR", "p": [10, 8, 3] },
	{ "s": "PROYECTO", "p": [12] },
	{ "s": "PUEDE", "p": [1, 12, 9] },
	{ "s": "PUEDES", "p": [3] },
	{ "s": "PUERTO", "p": [12] },
	{ "s": "PUERTO_BACKEND", "p": [12] },
	{ "s": "PÁGINA", "p": [1] }
];