DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex.prefixes = [
	{ "fileName": "0xu0030.js", "first": "0", "last": "0" },
	{ "fileName": "0xu0031.js", "first": "1", "last": "10" },
	{ "fileName": "0xu0032.js", "first": "2", "last": "2024" },
	{ "fileName": "0xu0033.js", "first": "3", "last": "3000" },
	{ "fileName": "0xu0034.js", "first": "4", "last": "4" },
	{ "fileName": "0xu0035.js", "first": "5", "last": "5" },
	{ "fileName": "0xu0036.js", "first": "6", "last": "6" },
	{ "fileName": "0xu0037.js", "first": "7", "last": "7" },
	{ "fileName": "0xu0038.js", "first": "8", "last": "8" },
	{ "fileName": "0xu0039.js", "first": "9", "last": "9" },
	{ "fileName": "0xu0041.js", "first": "A", "last": "AÑADIR" },
	{ "fileName": "0xu0042.js", "first": "BACKEND", "last": "BUSCAR" },
	{ "fileName": "0xu0043.js", "first": "CAMISAS", "last": "CÓPIALO" },
	{ "fileName": "0xu0044.js", "first": "DE", "last": "DR.EXPLAIN" },
	{ "fileName": "0xu0045.js", "first": "EDITOR", "last": "EXPLAIN" },
	{ "fileName": "0xu0046.js", "first": "FACILITAR", "last": "FUE" },
	{ "fileName": "0xu0047.js", "first": "GANANCIA", "last": "GUÍA" },
	{ "fileName": "0xu0048.js", "first": "HABRÁ", "last": "HUBO" },
	{ "fileName": "0xu0049.js", "first": "II", "last": "INTERFAZ" },
	{ "fileName": "0xu004a.js", "first": "JOSE", "last": "JURÍDICO" },
	{ "fileName": "0xu004c.js", "first": "LA", "last": "LUEGO" },
	{ "fileName": "0xu004d.js", "first": "MARCADOS", "last": "MÍNIMO" },
	{ "fileName": "0xu004e.js", "first": "NATURAL", "last": "NUMERO" },
	{ "fileName": "0xu004f.js", "first": "O", "last": "OTRO" },
	{ "fileName": "0xu0050.js", "first": "PADRE", "last": "PÁGINA" },
	{ "fileName": "0xu0051.js", "first": "QUE", "last": "QUIERE" },
	{ "fileName": "0xu0052.js", "first": "REACT", "last": "RUC" },
	{ "fileName": "0xu0053.js", "first": "SE", "last": "SUS" },
	{ "fileName": "0xu0054.js", "first": "TABLA", "last": "TU" },
	{ "fileName": "0xu0055.js", "first": "UBICADO", "last": "UTILIZA" },
	{ "fileName": "0xu0056.js", "first": "VALIDO", "last": "VS" },
	{ "fileName": "0xu0057.js", "first": "WEB", "last": "WEB" },
	{ "fileName": "0xu0059.js", "first": "Y", "last": "YC" }
];